### ISSUE TITLE
Finish Glossary page

### ISSUE THREAD

**Issue by schedski** [schedski/github-for-web-designers-rs#1]
## Change Request
Hey, please finish the glossary.html page. It needs terms and definitions
Thanks

**Comment by schedski2** [comment]
Sure ting , bling. Working on it now...

**Comment by schedski** [comment]
Thanks Schedski2, I appreciate the hard work

**Comment by schedski2** [comment]
Not quite done yet - keeping it open in case I have any further questions

**Comment by schedski** [comment]
OK
